// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetPal_New_.Data;

namespace PetPal_New_.Migrations
{
    [DbContext(typeof(PetPalContext))]
    [Migration("20210407224434_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetPal_New_.Models.DogBreed", b =>
                {
                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DogFriendly")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseRequirement")
                        .HasColumnType("int");

                    b.Property<int>("FamilyFriendly")
                        .HasColumnType("int");

                    b.Property<string>("FoodTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroomingRequirements")
                        .HasColumnType("int");

                    b.Property<string>("HealthConcerns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HypoAllergenic")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Breed");

                    b.ToTable("DogBreeds");
                });

            modelBuilder.Entity("PetPal_New_.Models.OwnerDog", b =>
                {
                    b.Property<int>("DogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Misc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserAccountUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DogID");

                    b.HasIndex("UserAccountUserID");

                    b.ToTable("UsersDog");
                });

            modelBuilder.Entity("PetPal_New_.Models.UserAccount", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetPal_New_.Models.OwnerDog", b =>
                {
                    b.HasOne("PetPal_New_.Models.UserAccount", null)
                        .WithMany("Dogs")
                        .HasForeignKey("UserAccountUserID");
                });

            modelBuilder.Entity("PetPal_New_.Models.UserAccount", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
